# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-21 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=510),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_objective',
            field=models.CharField(max_length=100),
        ),
    ]
