# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20181021_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_areas',
        ),
        migrations.AddField(
            model_name='job',
            name='job_areas',
            field=models.CharField(default='valor default', max_length=255),
            preserve_default=False,
        ),
    ]
