# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20181021_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
