# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20181021_0204'),
        ('volunteeringareas', '0003_volunteeringarea_picture'),
        ('volunteers', '0009_auto_20181028_0314'),
        ('jobs', '0006_auto_20181104_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_job', models.NullBooleanField()),
                ('volunteer_commentary', models.TextField(blank=True, max_length=510)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('job_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteeringareas.VolunteeringArea')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer')),
            ],
            options={
                'verbose_name_plural': 'Job Matchs',
            },
        ),
    ]
