# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatch',
            name='company_commentary',
            field=models.TextField(blank=True, max_length=510),
        ),
    ]
