# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobmatch_company_commentary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmatch',
            old_name='job_area',
            new_name='job_areas',
        ),
    ]
