# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-18 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_remove_volunteer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='interest_areas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
