# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-21 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_volunteer_interest_areas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name_plural': 'Volunteers'},
        ),
    ]
