# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-21 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_auto_20181021_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name_plural': 'Volunteers'},
        ),
    ]
