# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteeringareas', '0002_auto_20181021_0351'),
        ('volunteers', '0006_auto_20181021_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='interest_areas',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='interest_areas',
            field=models.ManyToManyField(to='volunteeringareas.VolunteeringArea'),
        ),
    ]
