# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_auto_20181021_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='interest_areas',
            field=models.ManyToManyField(blank=True, null=True, to='volunteeringareas.VolunteeringArea'),
        ),
    ]
