# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-08 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_location', models.CharField(blank=True, max_length=255, null=True)),
                ('company_sector', models.CharField(max_length=100)),
                ('trading_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ('trading_name',),
            },
        ),
    ]
